# Tantic GGplot

Loading Data
```{r}
library(readr)
titanic_clean <- read_csv("C:/Users/Michael/Desktop/SpringBoard/titanic_clean.csv")
View(titanic_clean)


titanic <- titanic_clean

```

## 1 - Check the structure of titanic

```{r}
str(titanic)
```

## Load library and change Pclass and Sex to pclass and sex

```{r}
library(ggplot2)
```


# 2 - Use ggplot() for the first instruction
```{r}
ggplot(titanic, aes(x = pclass, fill = sex)) + 
  geom_bar(position = "dodge")
```


# 3 - Plot 2, add facet_grid() layer
#change Survived to survived

```{r}
ggplot(titanic, aes(x = pclass, fill = sex)) + 
  geom_bar(position = "dodge") +
  facet_grid(. ~ survived)
```

# 4 - Define an object for position jitterdodge, to use below

```{r}
posn.jd <- position_jitterdodge(0.5, 0, 0.6)
```

# 5 - Plot 3, but use the position object from instruction 4
# change Age to age

```{r}
ggplot(titanic, aes(x = pclass, y = age, col = sex)) + 
  geom_point(size = 3, alpha= 0.5, position = posn.jd) +
  facet_grid(.~survived)
```

